### ISSUE TITLE
Dublication Crash - Mod is Installed Correctly

### ISSUE THREAD

**Issue by CreepyCauliflower** [Hellkitty/essentialnourishment#2]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  LoadingPlugin (ChunkAnimator-MC1.8.8-1.1.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.1.5.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 01.05.16 13:06
Description: Initializing game

java.lang.IllegalArgumentException: Multiple entries with same key: essentialnourishmentcore=FMLMod:essentialnourishmentcore{1.0.1} and essentialnourishmentcore=FMLMod:essentialnourishmentcore{1.1}
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:365)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:365)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 312660096 bytes (298 MB) / 952107008 bytes (908 MB) up to 10379853824 bytes (9899 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_H5 29 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
		Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
		AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
		cfm{3.6.2} [MrCrayfish's Furniture Mod] (cfm-3.6.2-mc1.8.9.jar) 
		ChunkAnimator{1.1} [Chunk Animator] (ChunkAnimator-MC1.8.8-1.1.jar) 
		cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
		CustomBackgrounds{1.0} [Custom Backgrounds] (CustomBackgrounds-1.0.jar) 
		lootablebodies{1.4.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.0.jar) 
		essentialnourishmentcore{1.1} [Essential Nourishment] (essentialnourishmentcore-1.8.9-1.1.jar) 
		essentialnourishmentcore{1.0.1} [Essential Nourishment] (essentialnourishmentcore-1.8.9-1.1.jar) 
		essentialnourishmentdrink{1.0} [Essential Nourishment Drinks] (essentialnourishmentdrink-1.8.9-1.0.jar) 
		HelperTools{v2.5c} [HelperTools] (Helpertools-1.8.9-2.5b.jar) 
		InventoryPets{1.4.4} [Inventory Pets] (inventorypets-1.8.9-1.4.4.jar) 
		inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
		JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
		JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
		malisisblocks{1.8-2.0.0} [Malisis Blocks] (malisisblocks-1.8-2.0.0.jar) 
		malisiscore{1.8.9-2.1.5} [MalisisCore] (malisiscore-1.8.9-2.1.5.jar) 
		malisisdoors{1.8.9-3.1.4} [MalisisDoors] (malisisdoors-1.8.9-3.1.4.jar) 
		MSM3{3.1.0.123} [More Swords 3] (MoreSwords-1.8.9-3.1.0.123.jar) 
		NoNausea{1.0} [No Nausea] (NoNausea-MC1.8-1.0.jar) 
		plantmegapack{1.8.9.21} [Plant Mega Pack] (plantmegapack-1.8.9.21.jar) 
		randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
		showarmsstand{1.2.2} [ShowArmsStand] (showarmsstand-1.2.2.jar) 
		sbm{1.2} [Simply Better Minecraft] (SimplyBetterMinecraft-v1.1-1.8.9.jar) 
		Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
		XaeroMinimap{1.9} [Xaero's Minimap] (Xaeros_Minimap_1.9_Forge_1.8.9.jar) 
		Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
LoadingPlugin (ChunkAnimator-MC1.8.8-1.1.jar)
  lumien.chunkanimator.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (NoNausea-MC1.8-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.8.9-2.1.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.72' Renderer: 'GeForce GT 745M/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: GeForce GT 745M/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_H5
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 364.72
	OpenGlRenderer: GeForce GT 745M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by JoelZBub** [comment]
This has been fixed. Wanna mark it as closed?

**Comment by Hellkitty** [comment]
Yeah. I forgot to.
